### ISSUE TITLE
PGraphics issue using P2D/P3D

### ISSUE THREAD

**Issue by merkkien** [processing/processing-android#102]
Hello,
I got an issue with PGraphics for Android, after several tests i found out that without specs, the render in createGraphics works fine, but when I use P2D or P3D it gets an error. This is an example code:

    PGraphics pg;
     
    void setup() {
      pg = createGraphics(40, 40, P2D);
    }
     
    void draw() {
      pg.beginDraw();
      pg.background(100);
      pg.stroke(255);
      pg.line(20, 20, mouseX, mouseY);
      pg.endDraw();
      image(pg, 9, 30);
      image(pg, 51, 30);
    }
     
    public String sketchRenderer() {
      return P2D;
    }

It throws:
<code>
Cannot run the OpenGL renderer outside the main thread, change your code
so the drawing calls are all inside the main thread,
or use the default renderer instead.
FATAL EXCEPTION: GLThread 485
java.lang.NullPointerException
    at processing.opengl.PGraphicsOpenGL.beginPixelsOp(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.readPixels(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.loadPixels(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.initCache(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.getTexture(Unknown Source)
    at processing.opengl.PGraphicsOpenGL$TexCache.getTexture(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.flushPolys(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.flush(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.endDraw(Unknown Source)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

This worked fine with previous versions of processing-android, but with the current version, that error happens.

Thanks ahead.

**Comment by omerjerk** [comment]
I also get this error "Cannot run the OpenGL renderer outside the main thread..." whenever I try to create custom PGraphics object. It's because glThread is null and never set. I'm not sure of what should be the best way to fix this. In my fork of android-mode, I've created a setter method for glThread object.

**Comment by omerjerk** [comment]
@codeanticode 
glThread is assigned [here](https://github.com/processing/processing-android/blob/master/core/src/processing/opengl/PGLES.java#L199), but I think this method is not called in this case and (this)[https://github.com/processing/processing-android/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L6313] false causing the above error.
Any idea how should we proceed with this ?

**Comment by codeanticode** [comment]
Hi, I'm able to reproduce this issue on 3.0a5, definitely a bug in the renderer.

**Comment by omerjerk** [comment]
This issue should be closed now. I'm not able to reproduce it in my video library with the latest changes.
Thanks @codeanticode  :)
