### ISSUE TITLE
Unable to install Android Mode in 3a07 - error log

### ISSUE THREAD

**Issue by ashleyjamesbrown** [processing/processing-android#108]
console log as follows when attempting to hit install from the Add Mode
Im on Mac OSX 10.9.5 - Java 8 update 45

java.lang.NoClassDefFoundError: processing/mode/java/JavaMode
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at processing.app.contrib.ModeContribution.<init>(ModeContribution.java:79)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:46)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:39)
	at processing.app.contrib.ContributionType.load(ContributionType.java:198)
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:153)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:152)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: processing.mode.java.JavaMode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by ashleyjamesbrown** [comment]
Ok so know since doing that i CANNOT OPEN processing 2beta5 which was my only solid way of getting android stuff on my phone. 
I also CANNOT OPEN 2.2.1 
I have rebooted but i have no idea what is going on ?

**Comment by ashleyjamesbrown** [comment]
In fact Android Mode is messed up on all versions of processing on my machine now.

**Comment by ashleyjamesbrown** [comment]
I can install Android mode on 3.0a5 no problems.

**Comment by codeanticode** [comment]
Hi, we need to update the android mode to work again with the latest alphas/upcoming beta. We have a Google Summer of Code who will be working on the android mode starting next week, hopefully we will be able to take care of these issues soon.

**Comment by codeanticode** [comment]
latest release of the mode works with 3.0 alpha 11. Needs to be installed manually due to a bug the contributions manager, but this will be fixed in the next Processing release.
