### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Lm0490** [processing/processing-android#117]
Hej Everyone,

I am running Processing 2.2.1 on Windows 7 with a 32-bit software on a 64-bit system. I installed the android mode as well as the Android SDK with all necessary tools (see below).
My system set-up used to work without a problem but then yesterday it suddenly stopped working and I have been receiving the same error since "BUILD FAILED" (see full-feedback below). 

Android SDK things I installed are: 
* Tools (Android SDK Tools, Android SDK Platform-Tools, Android SDK Build-Tools (22.0.1 & 21.1.2)),
* Tools (Preview Channel) Android SDK Build-tools,
* Android 5.1.1 (API 22) ,
* Android 5.0.1 (API 21), 
* Android 4.2.2 (API 17),
* Android 2.3.3 (API 10) , 
* Extras (Android Support Repository, Support Library, Google Play Services, Google Repository, Google USB Driver, Intel x86 Emulator Accelerator).

I have tried to run example code from within Processing but nothing works anymore.

BUILD FAILED
E:\Programme\AndroidSDK\tools\ant\build.xml:649: The following error occurred while executing this line:
E:\Programme\AndroidSDK\tools\ant\build.xml:694: Execute failed: java.io.IOException: Cannot run program "C:\Users\Lisa\AppData\Local\Temp\android5502934790343971484sketch\${aapt}" (in directory "C:\Users\Lisa\AppData\Local\Temp\android5502934790343971484sketch"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Execute.java:862)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:481)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:495)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:672)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
	at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:398)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at processing.mode.android.AndroidBuild.antBuild(AndroidBuild.java:515)
	at processing.mode.android.AndroidBuild.build(AndroidBuild.java:93)
	at processing.mode.android.AndroidMode.handleRunDevice(AndroidMode.java:227)
	at processing.mode.android.AndroidEditor$16.run(AndroidEditor.java:513)
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 45 more

Total time: 1 second

I have googled this issue and looked into many things to make it work again. I can clearly say that the preferences is pointing to the right path for the SDK. I checked that my java jdk (jdk1.8.0_40) is in my system preferences as a path as well.
I have checked this [Android  Processing] (http://forum.processing.org/one/topic/android-problems.html), [Can't get Android Mode working] (https://github.com/processing/processing/wiki/Supported-Platforms) and multiple other things wherefore I am by now completely lost. I also tried to use the other newer releases of Processing (3.0a10, 3.0a9 and 3.0a5 in 32 as well as 64-bit) but I cannot install the Android Mode here so that I cannot use this to fix the problem either. 
The error here:
java.lang.NoClassDefFoundError: processing/mode/java/JavaMode
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at processing.app.contrib.ModeContribution.<init>(ModeContribution.java:79)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:46)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:39)
	at processing.app.contrib.ContributionType.load(ContributionType.java:198)
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:153)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:152)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: processing.mode.java.JavaMode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

So any help is highly appreciated. Did I miss anything?
Thanks and hope to hear from anyone soon.

**Comment by Bazmundi** [comment]
I had the same problem.  For me it seemed to be related to running the Android SDK changing the build tools version.  Even when I went back to the original the problem persisted.  Android SDK somehow could not recover once you move away from the build tool version 19.1 odd.

The fix is quite draconian.  

Rip out Processing.

Rip out Android SDK.

You will find that processing will set up a folder in your Documents folder.  Rip that out as well.

If you have any environment variables set up for the Android SDK delete those too.

Re-installed Processing then let it download and setup the Android SDK.

I got the thing up and running and working again but I am queasy as it isn't obvious what caused the problem and there is not much useful help around.

**Comment by codeanticode** [comment]
Hi guys, please try the latest version of the mode with 3.0 alpha 11 (after updating your android SDK). This should solve the issues, however you need to install the android mode manually for the time being (download the zip file, uncompress inside the sketchbook/modes folder), because of a bug in the contribution manager. This will be fixed in the next Processing release.

Please let me know if you still see these errors.

**Comment by codeanticode** [comment]
You should be able to install the latest version of the android mode using the Contribution Manager in any of the beta releases of Processing 3.
