### ISSUE TITLE
Error after downloading SDK in Android Mode release 0241

### ISSUE THREAD

**Issue by darkwave** [processing/processing-android#136]
After choosing **Download SDK automatically** and when download is almost done  I got this error on the console. After that Processing is unable to find the SDK (and actually some files are missing from the _sdk folder_).

I'm using Processing IDE compiled using up-to-date git repository and latest Android Mode ZIP file released.

```
java.net.MalformedURLException: no protocol: android-22_r02.zip
	at java.net.URL.<init>(URL.java:586)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at processing.mode.android.SDKDownloader$SDKDownloadTask.downloadAndUnpack(SDKDownloader.java:138)
	at processing.mode.android.SDKDownloader$SDKDownloadTask.doInBackground(SDKDownloader.java:100)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by omerjerk** [comment]
Hi @darkwave 
Really sorry for this error. I couldn't fully test automatic downloading of SDK because of slow internet. Let me see what's going wrong here.

**Comment by omerjerk** [comment]
We parse this xml - https://dl-ssl.google.com/android/repository/repository-10.xml to download the Android SDK. Apparently, Google has removed the the full urls of all the SDKs for API level 14 and above. It'll take some time to fix. I'll need to resort to StackOverflow or Google Groups probably.
Meanwhile, I'd suggest you to download the Android SDK manually from Android SDK manager.

**Comment by codeanticode** [comment]
Solved in recent releases.
