### ISSUE TITLE
Sound in Android Mode

### ISSUE THREAD

**Issue by shlomihod** [processing/processing-android#150]
Hey, 

Is it possible to run Processing sketch with sound files in Android device using the Android mode?
Trying do so in mac, didn't work. I guess it's because the sound library of Processing is external one?

For example, I get this error with Processing 3.04b @ Android Mode running on device (Sony Xperia Z3) the code in the documentation for the sound library (https://processing.org/reference/libraries/sound/SoundFile.html):

```
FATAL EXCEPTION: Animation Thread
Process: processing.test.testsound, PID: 30450
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/processing.test.testsound-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libMethClaInterface.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:988)
	at processing.sound.MethClaInterface.<clinit>(Unknown Source)
	at processing.sound.Engine.<init>(Unknown Source)
	at processing.sound.Engine.<init>(Unknown Source)
	at processing.sound.Engine$LazyHolder.<clinit>(Unknown Source)
	at processing.sound.Engine.start(Unknown Source)
	at processing.sound.SoundFile.<init>(Unknown Source)
	at processing.test.testsound.TestSound.setup(TestSound.java:29)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)
```

Thanks,
Shlomi

**Comment by omerjerk** [comment]
There is no sound library for Processing for Android yet.
Even the video library was created during this GSoC - https://github.com/omerjerk/processing-video-android
Sound library won't be too difficult to incorporate but someone will need to sit and implement it. :P

**Comment by jimrolland** [comment]
You can try Apwidgets, it's very similar to minim : https://code.google.com/p/apwidgets/

**Comment by codeanticode** [comment]
closing, since there is nothing to fix in the mode itself.

**Comment by shlomihod** [comment]
I wrote a library for that based on omerjerk work:
https://github.com/shlomihod/cassette
