### ISSUE TITLE
get() and get(x, y, w, h) don't work in android mode

### ISSUE THREAD

**Issue by eddie-melcer** [processing/processing-android#154]
get(x,y) works in android mode, but get() and get(x, y, w, h) don't.

EXAMPLES:
void setup(){ }

void draw(){
  PImage test = get(0, 0, 1, 1);
}

AND

void setup(){ }

void draw(){
  PImage test = get();
}

OUTPUT:
FATAL EXCEPTION: Animation Thread
Process: processing.test.gettest, PID: 27405
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.getPixels(int[], int, int, int, int, int, int)' on a null object reference
	at processing.core.PImage.getImpl(Unknown Source)
	at processing.core.PImage.get(Unknown Source)
	at processing.core.PApplet.get(Unknown Source)
	at processing.test.gettest.GetTest.draw(GetTest.java:25)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/907a9f1d0ef28fe4832cfd81bd60de5ab4c6d5ce
