### ISSUE TITLE
exception with processing.video.Movie

### ISSUE THREAD

**Issue by trapperhoney** [processing/processing-android#166]
I haven't been able to get the Movie class from the Processing video library to work at all on android.  The exception is easy to reproduce by simply running the example Loop sketch that comes with the library in libraries/video/examples/Movie/Loop.

My guess is that this has something to do with a bug in the file name parsing code of the Movie class, but I'm not really even sure what a file name should look like from the android perspective..

FATAL EXCEPTION: Animation Thread
Process: processing.test.loop, PID: 16277
java.lang.ExceptionInInitializerError
	at processing.video.Movie.initGStreamer(Unknown Source)
	at processing.video.Movie.<init>(Unknown Source)
	at processing.test.loop.Loop.setup(Loop.java:36)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
	at processing.core.PApplet.parseInt(Unknown Source)
	at processing.core.PApplet.parseInt(Unknown Source)
	at processing.video.Video.<clinit>(Unknown Source)
	... 7 more

**Comment by omerjerk** [comment]
Processing video cannot run on Android.
For that, we have a separate library.
Have a look - https://github.com/omerjerk/processing-video-android

**Comment by trapperhoney** [comment]
Thank you! Works for me
