### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.http.util.EntityUtils.consume

### ISSUE THREAD

**Issue by warpwe** [processing/processing-android#184]
Code works fine in JAVA mode. Switching to Android and running on Android device gives the following exception. Verifying org.apache.http.util.EntityUtils.consume shows the method exists.

debug:
httpget:http://www.wetter.com/wetter_aktuell/aktuelles_wetter/deutschland/barsinghausen/bantorf/DE0000815002.html
http://www.wetter.com/wetter_aktuell/aktuelles_wetter/deutschland/barsinghausen/bantorf/DE0000815002.html
propertyValue:true
[socket][0] connection /62.138.109.37:80;LocalPort=45339(0)
[CDS]connect[/62.138.109.37:80] tm:90
[socket][/192.168.1.127:45339] connected
[CDS]rx timeout:0
[CDS]SO_SND_TIMEOUT:0
>doSendRequest
<doSendRequest
java.lang.NoSuchMethodError: org.apache.http.util.EntityUtils.consume
	at http.requests.GetRequest.send(Unknown Source)
	at processing.test.get_we.get_WE.draw(get_WE.java:33)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)
FATAL EXCEPTION: Animation Thread
Process: processing.test.get_we, PID: 29764
java.lang.NoSuchMethodError: org.apache.http.util.EntityUtils.consume
	at http.requests.GetRequest.send(Unknown Source)
	at processing.test.get_we.get_WE.draw(get_WE.java:33)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)

Sample code:
import http.requests.*;
import org.apache.http.*;

public void setup() 
{
	size(400,400);
  smooth();
}
public void draw() {    
  background(0);
  GetRequest get = new GetRequest("http://www.wetter.com/wetter_aktuell/aktuelles_wetter/deutschland/barsinghausen/bantorf/DE0000815002.html");
  get.send();
  String s = get.getContent();
  String[][] m = matchAll (s, "<span(.*?)/span>");
  int j = 0;
  int k = 12;
 if (m != null) {  // If not null, then a match was found
  for (int i = 94; i < 102; i++)
  {
   String sw = m[i][1];
   String[] w = match(sw,">(.*?)<");
   if (w != null)
   {
     j = j + k;
     text(i + " " + trim(w[1]), 1 , j);
   }
  }
 }
 String[][] n = matchAll (s, "<td(.*?)/td>");
 if (n != null) {  // If not null, then a match was found
  for (int i = 60; i < 72; i++)
  {
   String sw = n[i][1];
   String[] w = match(sw,">(.*?)<");
   if (w != null)
   {
//    println(i + " " + trim(w[1]));
      j = j + k;
      text(i + " " + trim(w[1]), 1 , j);  
 }
  }
 }
}

**Comment by warpwe** [comment]
Android device runs on 4.4.2. Error persists with SDK 4.4.2 and 6.0.

**Comment by prempalsingh** [comment]
Android uses an older version of apache libs than the one that JAVA SDK uses. In 6.0, the HttpClient library was completely removed (http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client). You should use HttpUrlConnection instead to make a GET request.

**Comment by mkodekar** [comment]
use volley

**Comment by mkodekar** [comment]
first see this convert html to json and from the output see if how the json comes out to be.
see herr how to convert html to json:-
http://stackoverflow.com/questions/23062537/how-to-convert-html-to-json-using-php
