### ISSUE TITLE
Can't read a json file from url

### ISSUE THREAD

**Issue by nicho2** [processing/processing-android#231]
i try to do a simply load json as this (this code run in java mode):
I have activate the INTERNET, WRITE_EXTERNAL_STORAGE permission

    final JSONObject json = loadJSONObject(url);
    int position = json.getInt("last_value");

my url is : http://io.adafruit.com/api/feeds/detection?x-aio-key=xxxxxxxxx

the error is : 

Couldn't create a reader for http://io.adafruit.com/api/feeds/detection?x-aio-key=xxxxxxxxx
java.lang.NullPointerException
	at processing.data.JSONTokener.<init>(Unknown Source)
	at processing.data.JSONObject.<init>(Unknown Source)
	at processing.core.PApplet.loadJSONObject(Unknown Source)
	at processing.test.demo_adafruit_bp.demo_adafruit_BP.requestData(demo_adafruit_BP.java:107)
	at processing.test.demo_adafruit_bp.demo_adafruit_BP.draw(demo_adafruit_BP.java:91)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

Thanks

**Comment by codeanticode** [comment]
@nicho2 the following sketch is able to read a test json from an URL without problem:

```java
JSONObject json;
String value;

fullScreen();  
json = loadJSONObject("http://echo.jsontest.com/key/value/one/two");
value = json.getString("key");

background(255);

fill(0);
textFont(createFont("Courier", 50));
text(json.toString(), 10, 60);  
text(value, 10, 300);  
```

It only requires the  INTERNET permission. Maybe there is a problem with the adafruit API or  your API key?

Also, note that the WRITE_EXTERNAL_STORAGE  permission is considered a ["dangerous" permission](https://developer.android.com/guide/topics/security/permissions.html#normal-dangerous) on Android 6 and newer, and needs to be approved by the user after the app has been installed (it is not enough to add it to the permissions list in the PDE). Verson 3.0.1 of the mode supports this new permission request process, and will be available thorugh the Contribution Manager soon.
