### ISSUE TITLE
Switching back and forth between views might exhaust memory

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#243]
If a sketch is embedded inside a parent layout in a multiple tab app, switching back and forth between the tabs might lead to an Out Of Memory Error when creating the backing bitmap for the Android2D renderer:

```
E/AndroidRuntime(30634): FATAL EXCEPTION: main
E/AndroidRuntime(30634): Process: imc_ebola.test.imcebola, PID: 30634
E/AndroidRuntime(30634): java.lang.OutOfMemoryError
E/AndroidRuntime(30634):    at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(30634):    at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
E/AndroidRuntime(30634):    at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
E/AndroidRuntime(30634):    at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
E/AndroidRuntime(30634):    at processing.core.PGraphicsAndroid2D.allocate(Unknown Source)
E/AndroidRuntime(30634):    at processing.core.PGraphics.setSize(Unknown Source)
E/AndroidRuntime(30634):    at processing.core.PApplet.makeGraphics(Unknown Source)
E/AndroidRuntime(30634):    at processing.core.PApplet.initSurface(Unknown Source)
E/AndroidRuntime(30634):    at processing.android.PFragment.onCreateView(Unknown Source)
E/AndroidRuntime(30634):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
E/AndroidRuntime(30634):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime(30634):    at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1430)
E/AndroidRuntime(30634):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:732)
E/AndroidRuntime(30634):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
E/AndroidRuntime(30634):    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
E/AndroidRuntime(30634):    at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
E/AndroidRuntime(30634):    at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
E/AndroidRuntime(30634):    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
E/AndroidRuntime(30634):    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
E/AndroidRuntime(30634):    at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:551)
E/AndroidRuntime(30634):    at imc_ebola.test.imcebola.MainActivity$1.onTabSelected(MainActivity.java:91)
E/AndroidRuntime(30634):    at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1025)
E/AndroidRuntime(30634):    at android.support.design.widget.TabLayout.selectTab(TabLayout.java:995)
E/AndroidRuntime(30634):    at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1272)
E/AndroidRuntime(30634):    at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1377)
E/AndroidRuntime(30634):    at android.view.View$PerformClick.run(View.java:19270)
E/AndroidRuntime(30634):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(30634):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(30634):    at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(30634):    at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime(30634):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(30634):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(30634):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(30634):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(30634):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  571):   Force finishing activity imc_ebola.test.imcebola/.MainActivity
```

**Comment by codeanticode** [comment]
This should be solved by reconfiguring the backing bitmap https://github.com/processing/processing-android/commit/2ba7381ba6c0d20ccf36c618fa2a991f4dbfab60, but will double check to make sure is fixed.

**Comment by codeanticode** [comment]
Tested with latest processing-core, and after +100 orientation changes, the app does not crash.
