### ISSUE TITLE
Latest Android mode does not work with devices running Android < 21

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#330]
Running a minimal sketch as regular app on a Galaxy Tab with Android 4.4.2, produces the following error:

```
E/AndroidRuntime(22849): java.lang.RuntimeException: Unable to start activity ComponentInfo{processing.test.sketch_324_wallpaper_resize/processing.test.sketch_324_wallpaper_resize.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
E/AndroidRuntime(22849): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
E/AndroidRuntime(22849): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
E/AndroidRuntime(22849): 	at android.app.ActivityThread.access$900(ActivityThread.java:175)
E/AndroidRuntime(22849): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
E/AndroidRuntime(22849): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22849): 	at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(22849): 	at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime(22849): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(22849): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(22849): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(22849): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(22849): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(22849): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
E/AndroidRuntime(22849): 	at android.content.res.Resources.loadDrawable(Resources.java:3440)
E/AndroidRuntime(22849): 	at android.content.res.Resources.getDrawable(Resources.java:1917)
E/AndroidRuntime(22849): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
E/AndroidRuntime(22849): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
E/AndroidRuntime(22849): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
E/AndroidRuntime(22849): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
E/AndroidRuntime(22849): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
E/AndroidRuntime(22849): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
E/AndroidRuntime(22849): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/AndroidRuntime(22849): 	at processing.test.sketch_324_wallpaper_resize.MainActivity.onCreate(MainActivity.java:17)
E/AndroidRuntime(22849): 	at android.app.Activity.performCreate(Activity.java:5451)
E/AndroidRuntime(22849): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
E/AndroidRuntime(22849): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
E/AndroidRuntime(22849): 	... 11 more
E/AndroidRuntime(22849): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
E/AndroidRuntime(22849): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
E/AndroidRuntime(22849): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
E/AndroidRuntime(22849): 	at android.content.res.Resources.loadDrawable(Resources.java:3436)
E/AndroidRuntime(22849): 	... 30 more
W/ActivityManager(  569):   Force finishing activity processing.test.sketch_324_wallpaper_resize/.MainActivity
```
 Seems related to [this discussion](http://stackoverflow.com/questions/39091521/vector-drawables-flag-doesnt-work-on-support-library-24) on Stackoverflow.

More to the point: [" Age of the vectors"](https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88), does not seem that the fix would work with ant, so another reason to deal with #307 asap.

**Comment by codeanticode** [comment]
Using gradle + aar packages fixes the issue, beta 9+
