### ISSUE TITLE
Rezise fuction doesn't work when using P2D

### ISSUE THREAD

**Issue by Sjers** [processing/processing-android#332]
When I try to use the rezise function while using P2D the app crashes and gives this error 

```
java.lang.ArrayIndexOutOfBoundsException:
length=2052000; index=2052000

OpenGL error 1280 at bot beginDraw(): invalid enum
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
OpenGL error 1280 at top endDraw(): invalid enum
java.lang.ArrayIndexOutOfBoundsException: length=2052000; index=2052000
 at processing.opengl.Texture.convertToRGBA(Unknown Source)
 at processing.opengl.Texture.set(Unknown Source)
 at processing.opengl.Texture.set(Unknown Source)
 at processing.opengl.PGraphicsOpenGL.initCache(Unknown Source)
 at processing.opengl.PGraphicsOpenGL.getTexture(Unknown Source)
 at processing.opengl.PGraphicsOpenGL$TexCache.getTexture(Unknown Source)
 at processing.opengl.PGraphicsOpenGL.flushPolys(Unknown Source)
 at processing.opengl.PGraphicsOpenGL.flush(Unknown Source)
 at processing.opengl.PGraphicsOpenGL.endDraw(Unknown Source)
 at processing.core.PApplet.handleDraw(Unknown Source)
 at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
```

**Comment by kfrajer** [comment]
More about this issue here: https://forum.processing.org/two/discussion/comment/96468/#Comment_96468

kfrajer

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/283191e6333615f0a860749a41899492dffe901c
