### ISSUE TITLE
Initializing location manager triggers a fatal exception

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#337]
Calling this code anywhwere:

```
    Context context = getContext();    
    locationListener = new MyLocationListener();
    locationManager = (LocationManager) context.getSystemService(Context.LOCATION_SERVICE);    
    locationManager.requestLocationUpdates(LocationManager.NETWORK_PROVIDER, 0, 0, locationListener);
```

in the sketch would give this error:

```
FATAL EXCEPTION: Animation Thread
Process: processing.test.sketch_1_location, PID: 14023
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:200)
	at android.os.Handler.<init>(Handler.java:114)
	at android.location.LocationManager$ListenerTransport$1.<init>(LocationManager.java:239)
	at android.location.LocationManager$ListenerTransport.<init>(LocationManager.java:239)
	at android.location.LocationManager.wrapListener(LocationManager.java:871)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:884)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:471)
	at processing.test.sketch_1_location.sketch_1_location.initLocation(sketch_1_location.java:77)
	at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/055d56b2523a56d253a560b9fed50a64b63a248d
