### ISSUE TITLE
filter() crashes on watch face sketches

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#391]
Calling filter() when using the default renderer in a watch face sketch, for example:

```
void setup() {
  fullScreen();
}

void draw() {
  background(0);
  filter(THRESHOLD);
}
```

gives this error:

```
FATAL EXCEPTION: main
Process: processing.test.filtercrash, PID: 3025
java.lang.NullPointerException: Attempt to get length of null array
	at processing.core.PImage.filter(Unknown Source)
	at processing.core.PImage.filter(Unknown Source)
	at processing.core.PApplet.filter(Unknown Source)
	at processing.test.filtercrash.FilterCrash.draw(FilterCrash.java:25)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.android.PWatchFaceCanvas$CanvasEngine.onDraw(Unknown Source)
	at android.support.wearable.watchface.CanvasWatchFaceService$Engine.draw(CanvasWatchFaceService.java:158)
	at android.support.wearable.watchface.CanvasWatchFaceService$Engine.onSurfaceRedrawNeeded(CanvasWatchFaceService.java:96)
	at android.service.wallpaper.WallpaperService$Engine.updateSurface(WallpaperService.java:803)
	at
android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1199)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

No crash happens with the OpenGL renderers.

**Comment by codeanticode** [comment]
The Java2D renderer on watch faces is not backed by a bitmap, so cannot have a pixels array. Throw  a more descriptive exception when trying to use loadPixels(), updatePixels(), and copy(): https://github.com/processing/processing-android/commit/cc06b703fe10c5c638ad13ef382fd7bc0d91a3ac

The workaround is to use the P2D or P3D in watch face that needs the pixels array.
