### ISSUE TITLE
VerifyError (Can't open the activity which contains the sketch PApplet)

### ISSUE THREAD

**Issue by m-devs** [processing/processing-android#406]
Hi!

I'm using android 4.1.2 , Samsung Galaxy S Advance (GT-I9070) and a SM-G357FZ with Android 4.4.4 and a Tab.. like Android 4.x idk now.. So I have this issue.
`FATAL EXCEPTION: main
                                                              java.lang.VerifyError: processing/core/PSurfaceNone
                                                                  at processing.a2d.PGraphicsAndroid2D.createSurface(Unknown Source)
                                                                  at processing.core.PApplet.initSurface(Unknown Source)
                                                                  at processing.android.PFragment.onCreateView(Unknown Source)
                                                                  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                  at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                  at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
                                                                  at android.app.Activity.performStart(Activity.java:5057)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2054)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106)
                                                                  at android.app.ActivityThread.access$700(ActivityThread.java:134)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1217)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:4856)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
                                                                  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:110)
                                                                  at dalvik.system.NativeStart.main(Native Method)`

 > My Activity (Java)
```Java
package mdev.fension;

import android.os.Bundle;
import android.content.Intent;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.support.v7.app.AppCompatActivity;

import processing.android.PFragment;
import processing.android.CompatUtils;
import processing.core.PApplet;

public class Main extends AppCompatActivity {

    PApplet fension;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FrameLayout frame = new FrameLayout(this);
        frame.setId(CompatUtils.getUniqueViewId());
        setContentView(frame, new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT));

        fension = new Fension();
        PFragment fragment = new PFragment(fension);
        fragment.setView(frame, this);

    }

    @SuppressWarnings("NullableProblems")
    @Override
    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
        if (fension != null) {
            fension.onRequestPermissionsResult(
                    requestCode, permissions, grantResults);
        }
    }

    @Override
    public void onNewIntent(Intent intent) {
        if (fension != null) {
            fension.onNewIntent(intent);
        }
    }

}
```

> My PApplet
```Java
package mdev.fension;

import processing.core.PApplet;

public class Fension extends PApplet {

    public void settings() {
        size(600, 600);
    }

    public void setup() { }

    public void draw() {
        if (mousePressed) {
            ellipse(mouseX, mouseY, 50, 50);
        }
    }

}
```
> My Layout XML
```XML
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".Main" >

    <FrameLayout android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>
```

So I just have no idea what's the problem. I'd appreciate your help.

**Comment by m-devs** [comment]
So I just find the answer... This is a multi dexing error.. I'm using another Java class version... and my android devices can't deal with 3rd party classes so I have to implement multi dexing in my project.

I think this will solve my problem.

**Comment by codeanticode** [comment]
Maybe the following issue is relevant: #317. The Android mode does not currently support multi-dex, it is marked as an enhancement. Sounds like I should close this one as a duplicate, am I correct?

**Comment by m-devs** [comment]
Yes you are correct. :) Thank's for the link.
