### ISSUE TITLE
NPE when calling background or setunder P3D renderer

### ISSUE THREAD

**Issue by kfrajer** [processing/processing-android#442]
Forum post [here](https://forum.processing.org/two/discussion/26361/how-do-a-get-image-files-on-to-my-android#latest) which I will copy the relevant pieces next:

From the trace call, I can see the problem is the background() function call in OPENGL mode. I am able to reproduce the problem with the following MCVE (plz ensure image is in the data folder):

```
import android.os.Environment;
import android.os.Build ;
import android.app.Activity;
import android.content.Context;
 
PImage back; 
 
void setup(){
  size(displayWidth, displayHeight, P3D);
  back = loadImage("bg.jpg");
}
 
void draw(){ 
   background(back);                      <----NPE!
   //set(0,0,back);                           <----NPE!
   //image(back,0,0,width,height);  <--It works 
}
```
Notice that when using P3D:

*    Either background() or set() throws an NPE and App crashes
*    It works normally if one uses image() instead,

Using the default renderer, you can use either background/set/image and you won't have any problem. I tested this using Win10, AM 4.0.1 and P3.3.6 on SG8 Nougat.

Back trace output next based on background():

> //FATAL EXCEPTION: GLThread 181069 
> //Process: processing.test.sketch_180219b, PID: 7447 
> //java.lang.NullPointerException: src == null 
> // at java.lang.System.arraycopy(Native Method) 
> // at processing.opengl.PGraphicsOpenGL.setImpl(Unknown Source) 
> // at processing.core.PImage.set(Unknown Source) 
> // at processing.opengl.PGraphicsOpenGL.backgroundImpl(Unknown Source) 
> // at processing.core.PGraphics.background(Unknown Source) 
> // at processing.core.PApplet.background(Unknown Source) 
> // at processing.test.sketch_180219b.sketch_180219b.draw(sketch_180219b.java:123) 
> // at processing.core.PApplet.handleDraw(Unknown Source) 
> // at processing.opengl.PSurfaceGLES$RendererGLES.onDrawFrame(Unknown Source) 
> // at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562) 
> // at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)

Back trace output next based on set():

> //FATAL EXCEPTION: GLThread 183761  
> //Process: processing.test.sketch_180219b, PID: 3877  
> //java.lang.NullPointerException: src == null  
> //  at java.lang.System.arraycopy(Native Method)  
> //  at processing.opengl.PGraphicsOpenGL.setImpl(Unknown Source)  
> //  at processing.core.PImage.set(Unknown Source)  
> //  at processing.core.PApplet.set(Unknown Source)  
> //  at processing.test.sketch_180219b.sketch_180219b.draw(sketch_180219b.java:132)  
> //  at processing.core.PApplet.handleDraw(Unknown Source)  
> //  at processing.opengl.PSurfaceGLES$RendererGLES.onDrawFrame(Unknown Source)  
> //  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)  
> //  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)  

These lines are of interest based on the trace:
https://github.com/processing/processing-android/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L5798   
https://github.com/processing/processing-android/blob/master/core/src/processing/core/PApplet.java#L9670      
https://github.com/processing/processing-android/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L5787     
https://github.com/processing/processing-android/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L5474

Kf

**Comment by kfrajer** [comment]
**Fix summary:** The reason of this error is bc of the implementation of the `set()` function, which is called by by `Background(...)`. Looking at the error code and after inspecting the code, the fix boils down to adding the following line to `setImpl(...)` function in **PGraphicsOpenGL.java**:

`if(sourceImage.pixels==null) sourceImage.loadPixels();  // TAG: CHANGE,FIX`

I provide a test code below, which it is not needed but form completeness. It has a setup, draw and clones of the set and setImpl function (labeled  setCM and setImplCM). You just need to jump directly to the line tagged *TAG: CHANGE, FIX*.  I will be submitting a pull request shortly. If I don't, you can easily upload this change in the main repo.

Kf

```
import android.app.Activity;
import android.content.Context;
import android.widget.FrameLayout;
//import android.app.Fragment;

import android.os.Environment;
import android.graphics.Color;
import android.widget.Toast;
import android.os.Looper;
import android.view.WindowManager;
import android.os.Bundle;
import android.view.ViewParent;
import android.view.ViewGroup;
import android.view.View;
import android.widget.RelativeLayout;
import android.view.LayoutInflater;
import android.R.string;


//===========================================================================
// FINAL FIELDS:


//===========================================================================
// GLOBAL VARIABLES:

Activity act;
Context mC;
PImage back;

//===========================================================================
// PROCESSING DEFAULT FUNCTIONS:

void setup() {
  //size(displayWidth, displayHeight, P3D);
  fullScreen(P2D);
  orientation(PORTRAIT);
  //orientation(LANDSCAPE;)


  act = this.getActivity();
  Looper.prepare();

  textAlign(CENTER, CENTER);
  rectMode(CENTER);

  fill(255);
  strokeWeight(2);
  textSize(32);


  back = loadImage("pic42.jpg");
  back.resize(width,height);
}

void draw() {
  
  println("back.pixelDensity: "+back.pixelDensity);
  setCM(0,0,back); 
  
  //background(back);                     //<----NPE!
  //set(0,0,back);                           <----NPE!
  //image(back,0,0,width,height);  <--It works
}


public void setCM(int x, int y, PImage img) {
    if (img.format == ALPHA) {
      // set() doesn't really make sense for an ALPHA image, since it
      // directly replaces pixels and does no blending.
      throw new IllegalArgumentException("set() not available for ALPHA images");
    }

    int sx = 0;
    int sy = 0;
    int sw = img.width;
    int sh = img.height;

    if (x < 0) {  // off left edge
      sx -= x;
      sw += x;
      x = 0;
    }
    if (y < 0) {  // off top edge
      sy -= y;
      sh += y;
      y = 0;
    }
    if (x + sw > width) {  // off right edge
      sw = width - x;
    }
    if (y + sh > height) {  // off bottom edge
      sh = height - y;
    }

    // this could be nonexistent
    if ((sw <= 0) || (sh <= 0)) return;

    setImplCM(img, sx, sy, sw, sh, x, y);
  }
  
  protected void setImplCM(PImage sourceImage,
                         int sourceX, int sourceY,
                         int sourceWidth, int sourceHeight,
                         int targetX, int targetY) {
    
                           //updatePixelSize();  INSTEAD use next two lines  TAG: CHANGE
    println("W=",width,pixelWidth);
    println("H=",height,pixelHeight);   
    

    // Copies the pixels
    loadPixels();
    if(sourceImage.pixels==null) sourceImage.loadPixels();  // TAG: CHANGE,FIX
    
    int sourceOffset = sourceY * sourceImage.pixelWidth + sourceX;
    int targetOffset = targetY * pixelWidth + targetX;
    for (int y = sourceY; y < sourceY + sourceHeight; y++) {
      System.arraycopy(sourceImage.pixels, sourceOffset, pixels, targetOffset, sourceWidth);
      sourceOffset += sourceImage.pixelWidth;
      targetOffset += pixelWidth;
    }

    // Draws the texture, copy() is very efficient because it simply renders
    // the texture cache of sourceImage using OpenGL.
    copy(sourceImage,
         sourceX, sourceY, sourceWidth, sourceHeight,
         targetX, targetY, sourceWidth, sourceHeight);
  }
```
