### ISSUE TITLE
OutOfMemory error when opening/closing a PFragment with an OpenGL sketch

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#482]
It happens in the saveState() method:

```
    java.lang.OutOfMemoryError: Failed to allocate a 7387216 byte allocation with 4786600 free bytes and 4MB until OOM, max allowed footprint 201326592, growth limit 201326592
        at processing.opengl.PGraphicsOpenGL$1.run(PGraphicsOpenGL.java:5717)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

when saving the pixels. This may be pointing to some renderer's resources not properly disposed, either the pixels or something else..

**Comment by codeanticode** [comment]
Fixed by saving the pixels to a cache file https://github.com/processing/processing-android/commit/3e3df3d9b28142c8fd8db97eb611f7517d969840
