### ISSUE TITLE
Hyperlink error on tutorial page click

### ISSUE THREAD

**Issue by rupeshkumar22** [processing/processing-android#631]
Faced an error while trying to open a tutorial hyperlink mentioned in the dialog box. 
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.mode.android.AndroidUtil$1.hyperlinkUpdate(AndroidUtil.java:78)
	at javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:342)
```
![linkerrorIssue](https://user-images.githubusercontent.com/46577873/103487408-2bc7b280-4e2b-11eb-96db-536cf897c7bc.JPG)

**Comment by rupesh-kumar-lpu** [comment]
I think this is the duplicate of #436

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commits/main
