### ISSUE TITLE
Cannot build Android app

### ISSUE THREAD

**Issue by WildPoYo** [processing/processing-android#689]
Application is stuck in "Building Android Project" state and throws the exception below.

4.0b7

Exception in thread "Thread-10" java.lang.NoSuchMethodError: 'processing.mode.java.preproc.PreprocessorResult processing.mode.android.AndroidBuild.preprocess(java.io.File, java.lang.String, processing.mode.java.preproc.PdePreprocessor, boolean)'
	at processing.mode.android.AndroidBuild.createProject(AndroidBuild.java:252)
	at processing.mode.android.AndroidBuild.build(AndroidBuild.java:223)
	at processing.mode.android.AndroidMode.handleRunEmulator(AndroidMode.java:241)
	at processing.mode.android.AndroidEditor$15.run(AndroidEditor.java:390)

**Comment by rupesh-kumar-lpu** [comment]
It seems that the method named preprocess [used here](https://github.com/processing/processing-android/blob/78b8bca79799b7d02a25112e4effc2a0ee3f43f6/mode/src/processing/mode/android/AndroidBuild.java#L252) is not defined or may have been removed from AndroidBuild.java in the past updatation. There is a method [PreprocessorResult write](https://github.com/processing/processing4/blob/ab70842496864b57923502831a93f3c5646233bb/java/src/processing/mode/java/preproc/PdePreprocessor.java#L146). Is it supposed to be used here after using PdePreprocessor.build()? @codeanticode

**Comment by codeanticode** [comment]
Hi Rupesh, you have to compile the mode using the latest branch from Processing that introduces some changes in the preprocessor(), precisely to fix this issue: https://github.com/processing/processing-android/issues/663
