### ISSUE TITLE
kava.lang.VerifyError: Rejecting class processing.a2d.PSurfaceAndroid2D

### ISSUE THREAD

**Issue by rvispute** [processing/processing-android#748]
Getting following error after updating to 4.5.1 from 4.5.0b5.
On 4.5 beta 5 application was building and loading on device.
on 4.5.1 the build is successful but the app crashes at the start on the device and following error message is displayed on  IDE console.

FATAL EXCEPTION: main
Process: processing.test.wifircesp32, PID: 17183
java.lang.VerifyError: Rejecting class processing.a2d.PSurfaceAndroid2D that attempts to sub-type erroneous class processing.core.PSurfaceNone (declaration of 'processing.a2d.PSurfaceAndroid2D' appears in /data/app/~~qrWxfXdcaxKOVnDrKVlvpg==/processing.test.wifircesp32-hUXCyiGCZyRROhlxxgXnlA==/base.apk)
	at processing.a2d.PGraphicsAndroid2D.createSurface(PGraphicsAndroid2D.java:180)
	at processing.core.PApplet.initSurface(PApplet.java:538)
	at processing.android.PFragment.onCreateView(PFragment.java:149)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.VerifyError: Verifier rejected class processing.core.PSurfaceNone: android.content.Context processing.core.PSurfaceNone.getContext() failed to verify: android.content.Context processing.core.PSurfaceNone.getContext(): [0x22]  can't resolve returned type 'Reference: android.content.Context' or 'Unresolved Reference: android.support.wearable.watchface.WatchFaceService' (declaration of 'processing.core.PSurfaceNone' appears in /data/app/~~qrWxfXdcaxKOVnDrKVlvpg==/processing.test.wifircesp32-hUXCyiGCZyRROhlxxgXnlA==/base.apk)
	... 28 more

**Comment by ranaaditya** [comment]
> Getting following error after updating to 4.5.1 from 4.5.0b5. On 4.5 beta 5 application was building and loading on device. on 4.5.1 the build is successful but the app crashes at the start on the device and following error message is displayed on IDE console.
> 
> FATAL EXCEPTION: main Process: processing.test.wifircesp32, PID: 17183 java.lang.VerifyError: Rejecting class processing.a2d.PSurfaceAndroid2D that attempts to sub-type erroneous class processing.core.PSurfaceNone (declaration of 'processing.a2d.PSurfaceAndroid2D' appears in /data/app/~~qrWxfXdcaxKOVnDrKVlvpg==/processing.test.wifircesp32-hUXCyiGCZyRROhlxxgXnlA==/base.apk) at processing.a2d.PGraphicsAndroid2D.createSurface(PGraphicsAndroid2D.java:180) at processing.core.PApplet.initSurface(PApplet.java:538) at processing.android.PFragment.onCreateView(PFragment.java:149) at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963) at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518) at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282) at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189) at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100) at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002) at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138) at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072) at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251) at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502) at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251) at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435) at android.app.Activity.performStart(Activity.java:8018) at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457) at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7664) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) Caused by: java.lang.VerifyError: Verifier rejected class processing.core.PSurfaceNone: android.content.Context processing.core.PSurfaceNone.getContext() failed to verify: android.content.Context processing.core.PSurfaceNone.getContext(): [0x22] can't resolve returned type 'Reference: android.content.Context' or 'Unresolved Reference: android.support.wearable.watchface.WatchFaceService' (declaration of 'processing.core.PSurfaceNone' appears in /data/app/~~qrWxfXdcaxKOVnDrKVlvpg==/processing.test.wifircesp32-hUXCyiGCZyRROhlxxgXnlA==/base.apk) ... 28 more

hi @rvispute which java version are you using ?

**Comment by Psudonem** [comment]
I have the same problem. It was working a few days ago, but suddenly I can't make android apps anymore.

**Comment by codeanticode** [comment]
@Psudonem @Entropy159 @rvispute what version of Processing are you using?

**Comment by VSMent** [comment]
Same happening for me.
Genymotion API 21 emulator and API 33 physical device work fine, but Genymotion API 30 emulator fails.
processing-core v408 - v411 fails to launch with the error
processing-core v407 - works on all 21/30/33 APIs
