### ISSUE TITLE
get() method doesn't work

### ISSUE THREAD

**Issue by darkwave** [processing/processing-android#91]
For example if I execute following code:

``` processing
String sketchRenderer() {
 return P3D; 
}

void setup() {

}

void draw() {
 translate(width / 2, height / 2);
 box(100);
 if (mousePressed) {
  color pixelColor = get(mouseX, mouseY); 
 }
}
```

And if I touch the display I get this error and the app exits :-(

```
FATAL EXCEPTION: GLThread 1165
Process: processing.test.sketch_141229b, PID: 13162
java.lang.RuntimeException: GL function glReadBuffer() is not available on this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help.
    at processing.opengl.PGLES.readBuffer(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.beginPixelsOp(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.readPixels(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.loadPixels(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.get(Unknown Source)
    at processing.core.PApplet.get(Unknown Source)
    at processing.test.sketch_141229b.sketch_141229b.draw(sketch_141229b.java:31)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

If I try to do the same operation on a PGraphics I get this NullPointerException:

```
FATAL EXCEPTION: GLThread 1168
Process: processing.test.sketch_141229b, PID: 15113
java.lang.NullPointerException
    at processing.opengl.PGraphicsOpenGL.beginPixelsOp(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.readPixels(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.loadPixels(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.initCache(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.getTexture(Unknown Source)
    at processing.opengl.PGraphicsOpenGL$TexCache.getTexture(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.flushPolys(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.flush(Unknown Source)
    at processing.opengl.PGraphicsOpenGL.endDraw(Unknown Source)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by omerjerk** [comment]
This error is fixed now.
Also, we have updated how `size()` works.
Have a look here how size() is transformed during the preprocessing stage - https://github.com/processing/processing-android/wiki#Screen_Orientation_and_the_size_command
